# -*- coding: utf-8 -*-
"""Dhanesh_Gore_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rk6-irCsoOUdeTGeh9ayI7VxtvsCI9cb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
cs = pd.read_csv("Customers.csv")
ps = pd.read_csv("Products.csv")
ts = pd.read_csv("Transactions.csv")

display(ts.head())

display(ps.head())

display(cs.head())

cs.count()

ps.count()

ts.count()

cs.isnull().sum()

ts.isnull().sum()

ps.isnull().sum()

shape = cs.shape
print(shape)

shape = ps.shape
print(shape)

shape = ts.shape
print(shape)

cs.info()

ts.info()

ps.info()

cs.describe()

ts.describe()

ps.describe()

# Convert dates to datetime
cs['SignupDate'] = pd.to_datetime(cs['SignupDate'])
ts['TransactionDate'] = pd.to_datetime(ts['TransactionDate'])

merged_data = ts.merge(customers, on='CustomerID').merge(ps, on='ProductID')

"""#EDA"""

# Customer Distribution by Region

region_distribution = cs['Region'].value_counts()
plt.figure(figsize=(8, 5))
region_distribution.plot(kind='bar')
plt.title('Customer Distribution by Region')
plt.xlabel('Region')
plt.ylabel('Number of Customers')
plt.show()

#top 5 products Sales Volume

top_products = merged_data.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False).head(5)
plt.figure(figsize=(8, 5))
top_products.plot(kind='bar')
plt.title('top 5 products sales volume')
plt.xlabel('product')
plt.ylabel('sold quantity')
plt.show()

# revenue by region
revenue_by_region = merged_data.groupby('Region')['TotalValue'].sum()
plt.figure(figsize=(8, 5))
revenue_by_region.plot(kind='bar')
plt.title('revenue by region')
plt.xlabel('region')
plt.ylabel('revenue')
plt.show()

#monthly sales trend
merged_data['Month'] = merged_data['TransactionDate'].dt.to_period('M')
monthly_sales = merged_data.groupby('Month')['TotalValue'].sum()
plt.figure(figsize=(10, 6))
monthly_sales.plot()
plt.title('monthly sales trend')
plt.xlabel('month')
plt.ylabel('total revenue')
plt.grid()
plt.show()

#average customer spending

average_spending = merged_data.groupby('CustomerID')['TotalValue'].sum().mean()
print(f"average customer spending: ${average_spending:.2f}")

merged_data.to_csv('Merged_Data.csv', index=False)

